config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get :tasks, to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update', as: :task
  get '/tasks/:id', to: 'tasks#show', as: :show
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, except: [:index, :new, :create]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to show_path(@task.id)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt=4">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Update a Task</h1>


<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %> or <%= link_to 'Cancel', task_path %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>


<%= link_to "Create Task", tasks_new_path, class: "btn btn-primary" %>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        ✔
        <% end %>
        <%= link_to task.title, show_path(task.id)%>

    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create a Task</h1>


<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %> or <%= link_to 'Cancel', tasks_path %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= link_to "Edit", edit_path(@task.id), class: "btn btn-primary" %>
<%= link_to "Delete", delete_path(@task), class: "btn btn-danger",
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<p>
  <%= @task.details %>
</p>
<p>
  Completed?
  <%= @task.completed %>
</p>

<%= link_to 'Back', tasks_path %>